# Generated by Django 2.2.6 on 2019-10-02 03:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2019, 10, 2, 3, 41, 55, 301603, tzinfo=utc))),
                ('expired_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 2, 4, 41, 55, 301635, tzinfo=utc), null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Login')),
            ],
        ),
    ]
