# Generated by Django 2.2.6 on 2019-10-02 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191002_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 2, 12, 4, 35, 198424, tzinfo=utc), null=True),
        ),
    ]
